topic_mapping:
  - { old: "/ublox_driver/range_meas", new: "/ublox_base/range_meas" }
  - { old: "/ublox_driver/ephem", new: "/ublox_base/ephem" }
  - { old: "/ublox_driver/iono_params", new: "/ublox_base/iono_params" }
  - { old: "/ublox_driver/receiver_pvt", new: "/ublox_base/receiver_pvt" }

input_bag: "/media/wxp/Elements SE/20250426/2025-04-26-21-58-18.bag"
output_bag: "/media/wxp/Elements SE/20250426/2.bag"
